language: scala
env:
  global:
    _JAVA_OPTIONS="-Xmx1500m -XX:MaxPermSize=512m -Dakka.test.timefactor=3"
scala:
   - 2.10.4
   - 2.11.6
addons:
  artifacts: true
    paths:
      - "job-server/target/scala-2.10/spark-job-server.jar"
      - "bin/server_start.sh"
      - "bin/server_stop.sh"
      - "config/log4j-server.properties"
  s3_region: "us-east-1"
